### ISSUE TITLE
error: no member named 'kSelectParserRelaxationEnabled' in namespace 'policy::key'

### ISSUE THREAD

**Issue by scottcali** [zunichky/chromium_aaos#6]
Hello,

When I run the build in Ubuntu 24.04, here is the error below. Could you please help me? 
Thank you!

-Scott

[120393/127309] CXX android_clang_arm/obj/chrome/browser/browser/configuration_policy_handler_list_factory.o
FAILED: android_clang_arm/obj/chrome/browser/browser/configuration_policy_handler_list_factory.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF android_clang_arm/obj/chrome/browser/browser/configuration_policy_handler_list_factory.o.d -DZLIB_CONST -DOFFICIAL_BUILD -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -DANDROID -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -DHAVE_SYS_UIO_H -DANDROID_NDK_VERSION_ROLL=r28_1 -DCR_CLANG_REVISION="llvmorg-21-init-11777-gfd3fecfc-1" -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_INSTRUMENTED_WITH_ASAN=0 -DCR_LIBCXX_REVISION=a01c02c9d4acbdae3b7e8a2f3ee58579a9c29f96 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER="../../skia/config/SkUserConfig.h" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_DISABLE_LEGACY_INIT_DECODERS -DSK_CODEC_DECODES_JPEG -DSK_CODEC_ENCODES_JPEG -DSK_BUILD_FOR_ANDROID -DUSE_CHROMIUM_SKIA -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_EXPONENT=1.4 -DSK_GAMMA_CONTRAST=0.0 -DSK_GANESH -DSK_GPU_WORKAROUNDS_HEADER="gpu/config/gpu_driver_bug_workaround_autogen.h" -DSK_GL -DSK_VULKAN=1 -DSK_GRAPHITE -DSK_DAWN -DVK_USE_PLATFORM_ANDROID_KHR -DCHROMIUM -DLIBYUV_DISABLE_SVE -DLIBYUV_DISABLE_SME -DLIBYUV_DISABLE_LSX -DLIBYUV_DISABLE_LASX -DON_FOCUS_PING_ENABLED -DGOOGLE_PROTOBUF_NO_RTTI -DHAVE_PTHREAD -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DPROTOBUF_ENABLE_DEBUG_LOGGING_MAY_LEAK_PII=0 -DWEBRTC_ENABLE_AVX2 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DWEBRTC_ANDROID -DWEBRTC_ALLOW_DEPRECATED_NAMESPACES -DABSL_ALLOCATOR_NOTHROW=1 -DLOGGING_INSIDE_WEBRTC -DLEVELDB_PLATFORM_CHROMIUM=1 -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_ARRAY_BUFFER_INTERNAL_FIELD_COUNT=0 -DV8_ARRAY_BUFFER_VIEW_INTERNAL_FIELD_COUNT=0 -DV8_PROMISE_INTERNAL_FIELD_COUNT=0 -DV8_DEPRECATION_WARNINGS -DV8_USE_PERFETTO -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_ANDROID -DCPPGC_ENABLE_LARGER_CAGE -DCPPGC_SLIM_WRITE_BARRIER -DI18N_ADDRESS_VALIDATION_DATA_URL="[https://chromium-i18n.appspot.com/ssl-aggregate-address/\](https://chromium-i18n.appspot.com/ssl-aggregate-address/%5C)" -DTFL_STATIC_LIBRARY_BUILD -DTF_MAJOR_VERSION=2 -DTF_MINOR_VERSION=20 -DTF_PATCH_VERSION=0 -DTF_VERSION_SUFFIX -DEIGEN_MPL2_ONLY -DEIGEN_MAX_ALIGN_BYTES=64 -DEIGEN_HAS_TYPE_TRAITS=0 -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DUSE_BLINK_EXTENSIONS_WEBVIEW=1 -DWTF_USE_WEBAUDIO_PFFFT=1 -DI18N_PHONENUMBERS_USE_ICU_REGEXP=1 -DI18N_PHONENUMBERS_USE_ALTERNATE_FORMATS=1 -DVR_USE_NATIVE_GL -DXRLOADER_DISABLE_EXCEPTION_HANDLING -DXR_KHR_LOADER_INIT_SUPPORT -DXR_OS_ANDROID -DXR_USE_PLATFORM_ANDROID -DXR_USE_GRAPHICS_API_OPENGL_ES -I../.. -Iandroid_clang_arm/gen -I../../buildtools/third_party/libc++ -I../../third_party/perfetto/include -Iandroid_clang_arm/gen/third_party/perfetto/build_config -Iandroid_clang_arm/gen/third_party/perfetto -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/quiche/common/platform/default -I../../net/third_party/quiche/src -I../../third_party/skia -Iandroid_clang_arm/gen/third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan-headers/src/include -Iandroid_clang_arm/gen/third_party/dawn/include -I../../third_party/dawn/include -I../../third_party/libyuv/include -I../../third_party/khronos -I../../gpu -Iandroid_clang_arm/gen/third_party/private_membership/src -Iandroid_clang_arm/gen/third_party/shell-encryption/src -Iandroid_clang_arm/gen/components/policy/proto -I../../third_party/protobuf/src -I../../third_party/abseil-cpp -I../../base/allocator/partition_allocator/src -Iandroid_clang_arm/gen/base/allocator/partition_allocator/src -I../../third_party/boringssl/src/include -I../../third_party/ipcz/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -Iandroid_clang_arm/gen/components/reporting/proto/synced -Iandroid_clang_arm/gen/net/third_party/quiche/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Iandroid_clang_arm/gen/third_party/webrtc -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libwebm/source -I../../third_party/angle/include -I../../third_party/mesa_headers -Igen/jni_headers -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/android -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/zlib -I../../v8/include -Iandroid_clang_arm/gen/third_party/metrics_proto -I../../third_party/re2/src -I../../third_party/libaddressinput/src/cpp/include -Iandroid_clang_arm/gen/third_party/tflite/src -I../../third_party/tflite/shims -I../../third_party/tflite/src -I../../third_party/tflite/src/third_party/xla -I../../third_party/tflite/src/third_party/xla/third_party/tsl -I../../third_party/pthreadpool/src/include -I../../third_party/eigen3/src -I../../third_party/gemmlowp/src -I../../third_party/neon_2_sse/src -I../../third_party/ruy/src -I../../third_party/flatbuffers/src/include -I../../third_party/flatbuffers/src/src -I../../third_party/flatbuffers/src -I../../third_party/flatbuffers/generated -I../../third_party/tflite_support/src -I../../third_party/tflite_support/src/tensorflow_lite_support -Iandroid_clang_arm/gen/third_party/tflite_support/src -Iandroid_clang_arm/gen/third_party/anonymous_tokens/src -I../../third_party/cpu_features/src/ndk_compat -I../../third_party/libphonenumber/dist/cpp/src -Iandroid_clang_arm/gen/third_party/libphonenumber -fprofile-sample-use=../../chrome/android/profiles/afdo.prof -Wno-backend-plugin -fprofile-sample-accurate -Wall -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wgnu -Wno-gnu-anonymous-struct -Wno-gnu-conditional-omitted-operand -Wno-gnu-include-next -Wno-gnu-label-as-value -Wno-gnu-redeclared-enum -Wno-gnu-statement-expression -Wno-gnu-zero-variadic-macro-arguments -Wno-zero-length-array -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-cast-function-type -Wno-thread-safety-reference-return -Wno-nontrivial-memcall -Wshadow -Werror -fno-delete-null-pointer-checks -fno-strict-overflow -fno-ident -fno-strict-aliasing -fstack-protector -funwind-tables -fPIC -fcolor-diagnostics -fmerge-all-constants -fno-sized-deallocation -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -split-threshold-for-reg-with-hint=0 -ffp-contract=off -flto=thin -fsplit-lto-unit -fcomplete-member-pointers -ffunction-sections -fno-short-enums --target=arm-linux-androideabi26 -march=armv7-a -mfloat-abi=softfp -ffile-compilation-dir=. -no-canonical-prefixes --warning-suppression-mappings=../../build/config/warning_suppression.txt -mfpu=neon -mthumb -Os -fdata-sections -ffunction-sections -fno-unique-section-names -fno-math-errno -mllvm -enable-ml-inliner=release -mllvm -ml-inliner-model-selector=arm32-size -fomit-frame-pointer -gdwarf-4 -g1 -gdwarf-aranges -fdebug-info-for-profiling -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang span-ctor-from-string-literal -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang raw-span-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-stack-allocated -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Xclang -add-plugin -Xclang raw-ptr-plugin -Xclang -plugin-arg-raw-ptr-plugin -Xclang check-raw-ptr-to-stack-allocated -Xclang -plugin-arg-raw-ptr-plugin -Xclang disable-check-raw-ptr-to-stack-allocated-error -Xclang -plugin-arg-raw-ptr-plugin -Xclang raw-ptr-exclude-path=../../third_party/dawn/ -Xclang -plugin-arg-raw-ptr-plugin -Xclang raw-ptr-exclude-path=../../build/config/clang/chrome/test/fuzzing/webidl_fuzzing/ -DUNSAFE_BUFFERS_BUILD -Xclang -add-plugin -Xclang unsafe-buffers -Xclang -plugin-arg-unsafe-buffers -Xclang ../../build/config/unsafe_buffers_paths.txt -Wexit-time-destructors -Wno-redundant-parens -Wno-redundant-parens -Wno-constant-conversion -Wno-shorten-64-to-32 -Wno-invalid-offsetof -Wenum-compare-conditional -Wno-nullability-completeness -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -nostdinc++ -isystem../../third_party/libc++/src/include -isystem../../third_party/libc++abi/src/include --sysroot=../../third_party/android_toolchain/ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fvisibility-inlines-hidden -c ../../chrome/browser/policy/configuration_policy_handler_list_factory.cc -o android_clang_arm/obj/chrome/browser/browser/configuration_policy_handler_list_factory.o
../../chrome/browser/policy/configuration_policy_handler_list_factory.cc:2252:5: error: no member named 'kSelectParserRelaxationEnabled' in namespace 'policy::key'; did you mean 'policy_prefs::kSelectParserRelaxationEnabled'?
2252 | { key::kSelectParserRelaxationEnabled,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| policy_prefs::kSelectParserRelaxationEnabled
../../components/policy/core/common/policy_pref_names.h:85:19: note: 'policy_prefs::kSelectParserRelaxationEnabled' declared here
85 | extern const char kSelectParserRelaxationEnabled[];
| ^
1 error generated.
[120410/127309] CXX android_clang_arm/obj/chrome/browser/browser/encrypted_reporting_client.o
ninja: build stopped: subcommand failed.

**Comment by scottcali** [comment]
[INFO] Updating version file: chromium/src/chrome/VERSION
[INFO] Version updated: MAJOR=139, BUILD=7191

**Comment by scottcali** [comment]
Latest code don't have the issue any more
